variable_metadata = {
    "KED_H": {
        "name": "Hydrogen Kinetic-Energy Distribution",
        "latex": "$\\mathrm{KED}_\\mathrm{H}$",
        "unicode": "KED_H",
        "unit_latex": "$-$",
        "unit_unicode": "-",
        "unit_name": "dimensionless",
    },
    "KED_react_atoms": {
        "name": "Kinetic-Energy Distribution of Donor + Acceptor Atoms",
        "latex": "$\\mathrm{KED}_{\\mathrm{D+A}}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "KED_D+A",
        "unit_unicode": "-",
    },
    "PC_formation_energy": {
        "name": "Product-Complex Formation Free Energy",
        "latex": "$w_\\mathrm{P}$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "w_P",
        "unit_unicode": "kcal/mol",
    },
    "RC_formation_energy": {
        "name": "Reactant-Complex Formation Free Energy",
        "latex": "$w_\\mathrm{R}$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "w_R",
        "unit_unicode": "kcal/mol",
    },
    "TS_energy": {
        "name": "Transition-State Electronic Energy",
        "latex": "$E_\\mathrm{TS}$",
        "unit_latex": "$\\mathrm{Hartree}$",
        "unit_name": "Hartree",
        "unicode": "E_TS",
        "unit_unicode": "Hartree",
    },
    "asynchronicity": {
        "name": "Asynchronicity",
        "latex": "$\\eta$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "η",
        "unit_unicode": "kcal/mol",
    },
    "computed_barrier": {
        "name": "Computed Reaction Barrier",
        "latex": "$\\Delta G^\\ddagger$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "ΔG‡",
        "unit_unicode": "kcal/mol",
    },
    "deltaG0": {
        "name": "Overall Reaction Free Energy",
        "latex": "$\\Delta G^{0}$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "ΔG°",
        "unit_unicode": "kcal/mol",
    },
    "deltaG0_inner": {
        "name": "Diagonal (Inner-Sphere) Reaction Free Energy",
        "latex": "$\\Delta G^{0}_{\\mathrm{diag}}$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "ΔG°_diag",
        "unit_unicode": "kcal/mol",
    },
    "frustration": {
        "name": "Thermodynamic Frustration",
        "latex": "$\\sigma$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "σ",
        "unit_unicode": "kcal/mol",
    },
    "tunneling_corr_reaction": {
        "name": "Tunnelling Correction (Reaction)",
        "latex": "$\\Delta G_\\mathrm{tun}^\\mathrm{rxn}$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "ΔG_tunrxn",
        "unit_unicode": "kcal/mol",
    },
    "tunneling_corr_self_reaction": {
        "name": "Tunnelling Correction (Self-Exchange)",
        "latex": "$\\Delta G_\\mathrm{tun}^\\mathrm{self}$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "ΔG_tunself",
        "unit_unicode": "kcal/mol",
    },
    "E_H": {
        "name": "Proton-Coupled Reduction Potential of Abstractor",
        "latex": "$E^{\\circ}_\\mathrm{H}$",
        "unit_latex": "$\\mathrm{V}$",
        "unit_name": "volt",
        "unicode": "E°_H",
        "unit_unicode": "volt",
    },
    "E_ox_0": {
        "name": "Standard Reduction Potential of Oxidant",
        "latex": "$E^{\\circ}_\\mathrm{ox}$",
        "unit_latex": "$\\mathrm{V}$",
        "unit_name": "volt",
        "unicode": "E°_ox",
        "unit_unicode": "volt",
    },
    "E_rad_deprot": {
        "name": "Radical/Deprotonated Reduction Potential",
        "latex": "$E_\\mathrm{rad-deprot}$",
        "unit_latex": "$\\mathrm{V}$",
        "unit_name": "volt",
        "unicode": "E_rad-deprot",
        "unit_unicode": "volt",
    },
    "mu": {
        "name": "Electronic Chemical Potential",
        "latex": "$\\mu$",
        "unit_latex": "$\\mathrm{eV}$",
        "unit_name": "electron-volt",
        "unicode": "μ",
        "unit_unicode": "electron-volt",
    },
    "omega": {
        "name": "Electrophilicity Index",
        "latex": "$\\omega$",
        "unit_latex": "$\\mathrm{eV}$",
        "unit_name": "electron-volt",
        "unicode": "ω",
        "unit_unicode": "electron-volt",
    },
    "pKaRH": {
        "name": "pKa of Substrate (RH)",
        "latex": "$\\mathrm{p}K_\\mathrm{a}(RH)$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "pK_a(RH)",
        "unit_unicode": "-",
    },
    "pKaRHplus": {
        "name": "pKa of Protonated Substrate (RH⁺)",
        "latex": "$\\mathrm{p}K_\\mathrm{a}(RH^+)$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "pK_a(RH+)",
        "unit_unicode": "-",
    },
    "self_exchange_KED_H": {
        "name": "Self-Exchange Hydrogen KED",
        "latex": "\\mathrm{KED}_\\mathrm{H}^{\\mathrm{self}}",
        "unit_latex": "-",
        "unit_name": "dimensionless",
        "unicode": "KED_Hself",
        "unit_unicode": "-",
    },
    "self_exchange_KED_react_atoms": {
        "name": "Self-Exchange Donor + Acceptor KED",
        "latex": "$\\mathrm{KED}_{\\mathrm{D+A}}^{\\mathrm{self}}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "KED_D+Aself",
        "unit_unicode": "-",
    },
    "self_exchange_RC_formation": {
        "name": "Self-Exchange Reactant-Complex Formation Energy",
        "latex": "$w_\\mathrm{R}^{\\mathrm{self}}$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "w_Rself",
        "unit_unicode": "kcal/mol",
    },
    "self_exchange_barrier": {
        "name": "Self-Exchange Reaction Barrier",
        "latex": "$\\Delta G^\\ddagger_\\mathrm{self}$",
        "unit_latex": "$\\mathrm{kcal/mol}$",
        "unit_name": "kcal/mol",
        "unicode": "ΔG‡_self",
        "unit_unicode": "kcal/mol",
    },
    "deprot": {
        "name": "Electronic Energy (Deprotonated)",
        "latex": "$E_\\mathrm{deprot}$",
        "unit_latex": "$\\mathrm{Hartree}$",
        "unit_name": "Hartree",
        "unicode": "E_deprot",
        "unit_unicode": "Hartree",
    },
    "ox": {
        "name": "Electronic Energy (Oxidised)",
        "latex": "$E_\\mathrm{ox}$",
        "unit_latex": "$\\mathrm{Hartree}$",
        "unit_name": "Hartree",
        "unicode": "E_ox",
        "unit_unicode": "Hartree",
    },
    "rad": {
        "name": "Electronic Energy (Radical)",
        "latex": "$E_\\mathrm{rad}$",
        "unit_latex": "$\\mathrm{Hartree}$",
        "unit_name": "Hartree",
        "unicode": "E_rad",
        "unit_unicode": "Hartree",
    },
    "zero": {
        "name": "Electronic Energy (Neutral RH)",
        "latex": "$E_0$",
        "unit_latex": "$\\mathrm{Hartree}$",
        "unit_name": "Hartree",
        "unicode": "E_0",
        "unit_unicode": "Hartree",
    },
    "dataset": {
        "name": "Dataset Label",
        "latex": "$\\mathrm{Dataset}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "Dataset",
        "unit_unicode": "-",
    },
    "molecule_id": {
        "name": "Molecule Identifier",
        "latex": "$\\mathrm{ID}_\\mathrm{mol}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "ID_mol",
        "unit_unicode": "-",
    },
    "smiles": {
        "name": "SMILES String",
        "latex": "$\\mathrm{SMILES}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "SMILES",
        "unit_unicode": "-",
    },
    "subst_target_atom": {
        "name": "Substrate Target Atom",
        "latex": "$\\mathrm{Atom}_\\mathrm{subst}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "Atom_subst",
        "unit_unicode": "-",
    },
    "subst_target_atom_other_hs": {
        "name": "Other H Atoms on Substrate Target",
        "latex": "$\\mathrm{H}_\\mathrm{other}^{\\mathrm{subst}}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "H_othersubst",
        "unit_unicode": "-",
    },
    "oxid_target_atom": {
        "name": "Oxidant Target Atom",
        "latex": "$\\mathrm{Atom}_\\mathrm{oxid}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "Atom_oxid",
        "unit_unicode": "-",
    },
    "oxid_target_atom_other_hs": {
        "name": "Other H Atoms on Oxidant Target",
        "latex": "$\\mathrm{H}_\\mathrm{other}^{\\mathrm{oxid}}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "H_otheroxid",
        "unit_unicode": "-",
    },
    "target_atom": {
        "name": "Generic Target Atom",
        "latex": "$\\mathrm{Atom}_\\mathrm{target}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "Atom_target",
        "unit_unicode": "-",
    },
    "target_atom_other_hs": {
        "name": "Other H Atoms on Generic Target",
        "latex": "$\\mathrm{H}_\\mathrm{other}^{\\mathrm{target}}$",
        "unit_latex": "$-$",
        "unit_name": "dimensionless",
        "unicode": "H_othertarget",
        "unit_unicode": "-",
    },
}
